from langChain.langChain import LangChain
import os
from langchain_community.agent_toolkits.sql.base import create_sql_agent
from langchain_community.utilities import SQLDatabase 
from langchain_community.agent_toolkits import SQLDatabaseToolkit
def message( query):
        """message method will take the query from the user and process the result and return the response

        Args:
            query (String): this is the question of the user
        Returns:
            response (String): This is the response generated by llms
        """
        langChain = LangChain()
        toolkit = SQLDatabaseToolkit(db=langChain.db, llm=langChain.llm)
        # Creating the agent executor
        agent_executor = create_sql_agent(
            llm=langChain.llm,
            toolkit=toolkit,
            verbose=True
        )
         
        response = agent_executor.run(query)
        return response